# Generated by Django 5.2.3 on 2025-07-18 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('nivel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('introduccion', models.TextField()),
                ('resumen', models.TextField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='cursos.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('opcion_multiple', 'Opción Múltiple'), ('completar_versiculo', 'Completar Versículo')], max_length=30)),
                ('pregunta', models.TextField(blank=True, null=True)),
                ('versiculo', models.TextField(blank=True, null=True)),
                ('opciones', models.JSONField(blank=True, null=True)),
                ('respuesta_correcta', models.JSONField()),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='cursos.leccion')),
            ],
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('puntaje', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.leccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'leccion')},
            },
        ),
    ]
