# Generated by Django 5.2.3 on 2025-08-27 02:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejercicio',
            options={'ordering': ['id'], 'verbose_name': 'Ejercicio', 'verbose_name_plural': 'Ejercicios'},
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='explicacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='puntaje',
            field=models.IntegerField(default=10, help_text='Puntaje del ejercicio (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='pregunta',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='respuesta_correcta',
            field=models.CharField(default='', max_length=500),
        ),
    ]
