# Generated by Django 5.2.4 on 2025-07-18 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='titulo',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='leccion',
            old_name='introduccion',
            new_name='contenido',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='versiculo',
        ),
        migrations.RemoveField(
            model_name='leccion',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='leccion',
            name='resumen',
        ),
        migrations.RemoveField(
            model_name='progreso',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='progreso',
            name='puntaje',
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='opciones',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='pregunta',
            field=models.TextField(default='Pregunta pendiente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='respuesta_correcta',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'curso')},
            },
        ),
    ]
