# Generated by Django 5.2.4 on 2025-07-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_rename_titulo_curso_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progreso',
            name='puntaje',
            field=models.FloatField(default=0),
        ),
    ]
