# Generated by Django 5.2.3 on 2025-08-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_inscripcion_options_inscripcion_completado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leccion',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='leccion',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
