# Generated by Django 5.2.4 on 2025-07-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_progreso_puntaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='nombre',
        ),
        migrations.AddField(
            model_name='curso',
            name='titulo',
            field=models.CharField(default='Curso sin título', max_length=255),
            preserve_default=False,
        ),
    ]
