# Generated by Django 5.2.3 on 2025-08-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_leccion_options_leccion_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leccion',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='leccion',
            name='orden',
        ),
    ]
