# Generated by Django 5.2.4 on 2025-08-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_remove_curso_nombre_curso_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='guia_pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leccion',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
