# Generated by Django 5.2.3 on 2025-09-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_alter_leccion_options_remove_leccion_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preguntaexamenfinal',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='progreso',
            name='ejercicios_completados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progreso',
            name='ejercicios_correctos',
            field=models.IntegerField(default=0),
        ),
    ]
