# Generated by Django 5.2.4 on 2025-08-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_leccion_guia_pdf_url_leccion_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
