# Generated by Django 5.2.4 on 2025-08-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_categoria_remove_leccion_descripcion_curso_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de la imagen'),
        ),
    ]
