# Generated by Django 5.2.4 on 2025-08-13 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_respuesta_correcta_charfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examen_final', to='cursos.curso')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaExamenFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('opciones', models.JSONField(default=list)),
                ('respuesta_correcta', models.CharField(max_length=255)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='cursos.examenfinal')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoExamenFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.FloatField()),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('certificado_pdf', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.examenfinal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
