# Generated by Django 5.2.4 on 2025-08-13 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_examenfinal_preguntaexamenfinal_resultadoexamenfinal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultadoExamenFinal',
        ),
    ]
