# Generated by Django 5.2.4 on 2025-08-13 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_delete_resultadoexamenfinal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntaexamenfinal',
            name='examen',
        ),
        migrations.AddField(
            model_name='preguntaexamenfinal',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_examen_final', to='cursos.curso'),
            preserve_default=False,
        ),
    ]
