# Generated by Django 5.2.3 on 2025-08-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_email_verificado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email_verificado',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='token_reset_password',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='token_reset_password_fecha',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='token_verificacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='token_verificacion_fecha',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
